// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASL0BfmYbZeEMG9iwQdf08OwOW_iviAKo',
    appId: '1:134318970255:web:5e6e5bece6e061774627fa',
    messagingSenderId: '134318970255',
    projectId: 'ceptesef-32545',
    authDomain: 'ceptesef-32545.firebaseapp.com',
    storageBucket: 'ceptesef-32545.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGrzmFWeUzXfhdrMxLXtzTSveczp7JZMo',
    appId: '1:134318970255:android:cc002bff392aff854627fa',
    messagingSenderId: '134318970255',
    projectId: 'ceptesef-32545',
    storageBucket: 'ceptesef-32545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBaAfb2b2i8FbZtnYuMoX2jbFnrN6_Xs',
    appId: '1:134318970255:ios:291e6d421d686cdc4627fa',
    messagingSenderId: '134318970255',
    projectId: 'ceptesef-32545',
    storageBucket: 'ceptesef-32545.firebasestorage.app',
    iosBundleId: 'com.turneight.ceptesef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBaAfb2b2i8FbZtnYuMoX2jbFnrN6_Xs',
    appId: '1:134318970255:ios:291e6d421d686cdc4627fa',
    messagingSenderId: '134318970255',
    projectId: 'ceptesef-32545',
    storageBucket: 'ceptesef-32545.firebasestorage.app',
    iosBundleId: 'com.turneight.ceptesef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASL0BfmYbZeEMG9iwQdf08OwOW_iviAKo',
    appId: '1:134318970255:web:245033ce51dd125b4627fa',
    messagingSenderId: '134318970255',
    projectId: 'ceptesef-32545',
    authDomain: 'ceptesef-32545.firebaseapp.com',
    storageBucket: 'ceptesef-32545.firebasestorage.app',
  );
}
